# Generated by Django 5.1.3 on 2024-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='status',
            field=models.CharField(choices=[('Programmée', 'Programmée'), ('Annulée', 'Annulée')], default='Programmée', max_length=20),
        ),
    ]
