# Generated by Django 5.1.3 on 2024-11-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_visite_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visite',
            options={'permissions': [('print_visite', 'Can print visite')]},
        ),
    ]
